services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./server/:/home/node/app:z
    command: ["sh", "-c", "npm i && npm run start:dev"]

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client/:/home/node/app:z
    command: ["sh", "-c", "npm i && npm run dev -- --host 0.0.0.0"]
