services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"